describe('Test Case Product Store',function(){
    before(()=>{
        cy.login()
    })
    it('Login Status', function() {
        cy.get('#nameofuser').should('have.text','Welcome dede')
    })

    it('Add to chart', function(){
        cy.contains('HTC One M9').click()
        cy.get('.name').should('have.text','HTC One M9')
        cy.get('.col-sm-12 > .btn').should('have.text','Add to cart')
        cy.get('.col-sm-12 > .btn').click()
        cy.go('back')
        cy.go('back')

        cy.contains('Laptops').click()
        cy.contains('Dell i7 8gb').click()
        cy.get('.name').should('have.text','Dell i7 8gb')
        cy.get('.col-sm-12 > .btn').should('have.text','Add to cart')
        cy.get('.col-sm-12 > .btn').click()
        cy.go('back')
        cy.go('back')

        cy.contains('Monitors').click()
        cy.contains('Apple monitor 24').click()
        cy.get('.name').should('have.text','Apple monitor 24')
        cy.get('.col-sm-12 > .btn').should('have.text','Add to cart')
        cy.get('.col-sm-12 > .btn').click()
        cy.go('back')
        cy.go('back')

        cy.get('#cartur').click()
        cy.get('#tbodyid > :nth-child(1) > :nth-child(2)').should('have.text','Apple monitor 24')
        cy.get('#tbodyid > :nth-child(2) > :nth-child(2)').should('have.text','Dell i7 8gb')
        // cy.get('#tbodyid > :nth-child(1) > :nth-child(2)').should('have.text','Dell i7 8gb')
        // cy.get('#tbodyid > :nth-child(2) > :nth-child(2)').should('have.text','Apple monitor 24')
        cy.get('#totalp').should('have.text','1100')
        cy.get('.col-lg-1 > .btn').click()
    
        cy.get('#name').type('dudu')
        cy.wait(6000)
        cy.get('#name').should('have.value','dudu')
        cy.get('#country').type('India')
        cy.wait(6000)
        cy.get('#country').should('have.value','India')
        cy.get('#city').type('Delhi')
        cy.wait(6000)
        cy.get('#city').should('have.value','Delhi')
        cy.get('#card').type('123456789')
        cy.wait(6000)
        cy.get('#card').should('have.value','123456789')
        cy.get('#month').type('Februari')
        cy.wait(6000)
        cy.get('#month').should('have.value','Februari')
        cy.wait(6000)
        cy.get('#year').type('2022')
        cy.wait(6000)
        cy.get('#year').should('have.value','2022')
        cy.get('#orderModal > .modal-dialog > .modal-content > .modal-footer > .btn-primary').click()
    })
    Cypress.on('uncaught:exception', (err, runnable)=>{
        return false
    })
})